# Generated by Django 5.2.13 on 2026-05-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='house_street',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
