# Generated by Django 5.2.13 on 2026-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
